version: '3.7'
services:
  api:
    image: aarondelaplane/dexpress-api-scala:0.2
    ports:
      - 10000:10000
    depends_on:
      - postgres
  postgres:
    image: postgres:12.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER:     postgres
      POSTGRES_DB:       dexpress