version: '3.7'
services:
#  dexpress-inventory-service:
#    image: dexpress-inventory-service:latest
#    ports:
#      - 10000:10000
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: inventory
    ports:
      - 5432:5432
    