addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.2.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.6.0")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.10")
//addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.5.0")
//addSbtPlugin("io.get-coursier" % "sbt-coursier" % "2.0.0-RC4-1")